### PR TITLE
Feat/ctest passing

### PR DESCRIPTION
**Pull request by jeswr**

### CODE REVIEW

**Comment by jeswr** [comment]
This is not ready for review; in particular we need to:
 - Get rid of the `.emscripten` file that is currently present
 - Fix swipl back to a particular branch

**Comment by jeswr** [comment]
> Fix swipl back to a particular version

@JanWielemaker - could you create a new release of [SWIPL](https://github.com/SWI-Prolog/swipl-devel) so that we can fix it to a version on which this all works :)

**Comment by JanWielemaker** [comment]
This pull request has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/wasm-updates-reply-1/6524/5

**Comment by jeswr** [comment]
Hmm ..  so running the following gives the output

```ts
const SWIPL = require('./dist');

async function main() {
  const Module = await SWIPL();
  console.log(Module.prolog.query("use_module(library(pcre)).").once());
  console.log(Module.prolog.query("use_module(library(pcre2)).").once());
}

main();
```

```
source_sink `library(pcre)' does not exist
{ error: true, message: "source_sink `library(pcre)' does not exist" }
source_sink `library(pcre2)' does not exist
{ error: true, message: "source_sink `library(pcre2)' does not exist" }
```

@JanWielemaker Does anything stand out in [this dockerfile](https://github.com/SWI-Prolog/npm-swipl-wasm/blob/3f451a13494bcb6432e0e50be371ad5f494c0128/docker/Dockerfile) as to why PCRE is not getting included? [This error in the build](https://github.com/SWI-Prolog/npm-swipl-wasm/actions/runs/4897854343/jobs/8746378085?pr=143#step:5:1182) seems to be the cause - perhaps the args mentioned there are missing in [these build instructions](https://www.swi-prolog.org/build/WebAssembly.md)?

**Comment by jeswr** [comment]
I'm also noticing that tests are taking about 2.5x the time they were taking to run before these changes so that is a slight alarm bell.

**Comment by jeswr** [comment]
Anyhow I've added some small development instructions [here](https://github.com/SWI-Prolog/npm-swipl-wasm/blob/39eb7358f92f03077ee4b26b7dd9cc4e3f3d3a2a/README.md#development) if you want to have a play with this branch yourself @JanWielemaker .

Please do *NOT* merge any changes to the main branch without review since I've got semantic release setup to start cutting a release as soon as merges are made to the master branch.

**Comment by JanWielemaker** [comment]
This pull request has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/wiki-discussion-swi-prolog-in-the-browser-using-wasm/5651/155

**Comment by JanWielemaker** [comment]
> Anyhow I've added some small development instructions [here](https://github.com/SWI-Prolog/npm-swipl-wasm/blob/39eb7358f92f03077ee4b26b7dd9cc4e3f3d3a2a/README.md#development) if you want to have a play with this branch yourself @JanWielemaker .

README looks nice!   I guess you'll do the testing and merge it when ready.    We're approaching a usable system :smile:   Thanks.

**Comment by jeswr** [comment]
> I guess you'll do the testing and merge it when ready. 

I was actually waiting on a response to https://github.com/SWI-Prolog/npm-swipl-wasm/pull/143#issuecomment-1537094794. In particular; can you explain how to resolve [this error in the build](https://github.com/SWI-Prolog/npm-swipl-wasm/actions/runs/4897854343/jobs/8746378085?pr=143#step:5:1182)?

**Comment by JanWielemaker** [comment]
> @JanWielemaker I was actually waiting on a response to [#143 (comment)](https://github.com/SWI-Prolog/npm-swipl-wasm/pull/143#issuecomment-1537094794). In particular; can you explain how to resolve [this error in the build](https://github.com/SWI-Prolog/npm-swipl-wasm/actions/runs/4897854343/jobs/8746378085?pr=143#step:5:1182)?

I'm having a look.   Will probably get an answer tomorrow.     Surely the Dockerfile needs a few changes.

**Comment by JanWielemaker** [comment]
Pushed 5862e66b98a27d5bcd48508926ba9e6d5eaf4a43.  This brings the Dockerfile more in sync with the build instructions.   See commit message or diffs for details.    I did the build without npm, running

     docker build --build-arg EMSDK_VERSION=3.1.27 --build-arg ZLIB_VERSION=1.2.13 --build-arg PCRE_VERSION=pcre2-10.42 .

You probably need to add PCRE_VERSION handling to the npm config.  Also updated node to latest stable.   You may want to add the version through a Docker `ARG` as well?

Note that I needed to add `-DNODE_JS_EXECUTABLE=/usr/bin/node` to use `/usr/bin/node` rather than the one from Emscripten.  That is node 14, which seems incapable of running `swipl.js` (running complains on illegal wasm function signature, but without telling which function or signature :cry: ) 

That makes me wonder a little about the minimal requirements to run the result.    Works on current Firefox and Chrome.

**Comment by JanWielemaker** [comment]
You may also add an `ARG` for `SWIPL_VERSION` and use a ``--branch $SWIPL_VERSION``?   Note that the argument of branch can be a branch as well as a tag, e.g. ``--branch V9.1.9`` should work.     That is also used for `PCRE_VERSION`.  Unfortunately you cannot use `--branch HEAD`, so you'd need some more shell hacking.

**Comment by jeswr** [comment]
> You may also add an ARG for SWIPL_VERSION and use a --branch $SWIPL_VERSION? Note that the argument of branch can be a branch as well as a tag, e.g. --branch V9.1.9 should work.

Yup - [that is how we do it in the main branch](https://github.com/SWI-Prolog/npm-swipl-wasm/blob/53e73a7ec0698eebc916d45cf18a2e9d211cc3dc/docker/Dockerfile#L29).

This build doesn't pass all of the `ctest`s on V9.1.9 so just waiting for the next so we can re-enable it and merge this PR :)

**Comment by jeswr** [comment]
Closing in favor of #186

**Pull request closed without merging**
