### PR TITLE
fix: update to swipl v9.1.17

### PR DESCRIPTION
**Pull request by jeswr**
fix: update to swipl v9.1.17

### CODE REVIEW

**Comment by jeswr** [comment]
@JanWielemaker We are failing to upgrade to swipl 9.1.17. The failing test is [here](https://github.com/SWI-Prolog/npm-swipl-wasm/actions/runs/6550958170/job/17791149886?pr=383#step:5:1969) and appears to be because the [time library is not available in the WASM build](https://github.com/SWI-Prolog/npm-swipl-wasm/actions/runs/6550958170/job/17791149886?pr=383#step:5:2019).

Is this something that can easily be resolved in https://github.com/SWI-Prolog/swipl-devel?

**Comment by JanWielemaker** [comment]
Sure.  Pushed SWI-Prolog/swipl-devel@c9f050b59ed9e80dcffa1df6cdfb4b092f0f633e.

This is not a new issue, no?

**Comment by JanWielemaker** [comment]
I added some use_module directives to various tests.    That might be a reason.   Anyway, the test is now cleanly disabled if it cannot run.

**Comment by jeswr** [comment]
Closing as v9.1.18 is now available.

**Pull request closed without merging**
