### PR TITLE
fix: update to swipl v9.3.15

### PR DESCRIPTION
**Pull request by jeswr**
fix: update to swipl v9.3.15

### CODE REVIEW

**Comment by jeswr** [comment]
@JanWielemaker @josd I am assuming that we would not expect [the recently added rwlocks tests](https://github.com/SWI-Prolog/npm-swipl-wasm/actions/runs/11934284299/job/33263071891?pr=787#step:7:2435) to succeed in a browser build. If this is the case; could you please advise on how to skip them in the `ctest` [here](https://github.com/SWI-Prolog/npm-swipl-wasm/blob/d00e479244240ab302d2055223f8f083499766d7/docker/Dockerfile#L52) as I am not particularly familiar with `ctest` myself.

Ideally, could you push the changes skipping the ctest for rwlocks as a commit to this PR.

**Comment by jeswr** [comment]
> > Ideally, could you push the changes skipping the ctest for rwlocks as a commit to this PR.
> 
> Not sure what you mean by that. I have pushed a fix as [SWI-Prolog/swipl-devel@bb29bab](https://github.com/SWI-Prolog/swipl-devel/commit/bb29bab2aa0852a8c83cb9ac4d3c4ce685ac3673). This moves the test to the `thread` directory. I hope you can work it out from there.

Thanks @JanWielemaker - moving the test to the `thread` directory solved the `ctest` issue.

We now have a new issue when running against https://github.com/SWI-Prolog/swipl-devel/commit/21f46ad65c0374c16140a231dea78891058b9787 in particular, the `yield` value after calling `swipl.prolog.call` appears to have been changed from `true` to false. The test is [here](https://github.com/SWI-Prolog/npm-swipl-wasm/blob/d00e479244240ab302d2055223f8f083499766d7/tests/node.js#L109-L116) and the CI failure can be found [here](https://github.com/SWI-Prolog/npm-swipl-wasm/actions/runs/11954260100/job/33324333279?pr=787#step:6:146).

**Comment by JanWielemaker** [comment]
If I read this correctly, there is nothing wrong with the yield value, but the `.done` field is not what you expect.  It needs to have this value to satisfy the Query as iterator.   I need to think.    Possibly we can get around by setting some flag on the query that tells us it is an iterator or not?    Otherwise we need to redesign the API a little.

**Comment by JanWielemaker** [comment]
Pushed SWI-Prolog/swipl-devel@d5192b2d20952d62de8b6829a7d719c1bc3c7af7 to address this and SWI-Prolog/swipl-devel@2910776f8c0efa001c9c16866fce09b4071e9f16 to get rid of the deprecated messages for `$allocate` and friends.   Builds using emcc 3.1.72 and passes the Prolog (ctest) tests.

**Comment by jeswr** [comment]
> If I read this correctly, there is nothing wrong with the yield value, but the .done field is not what you expect.

Correct, my bad!

> Pushed https://github.com/SWI-Prolog/swipl-devel/commit/d5192b2d20952d62de8b6829a7d719c1bc3c7af7 to address this and https://github.com/SWI-Prolog/swipl-devel/commit/2910776f8c0efa001c9c16866fce09b4071e9f16 to get rid of the deprecated messages for $allocate and friends. Builds using emcc 3.1.72 and passes the Prolog (ctest) tests.

Thanks for being so fast! CI now running with https://github.com/SWI-Prolog/swipl-devel/commit/2910776f8c0efa001c9c16866fce09b4071e9f16 - lets see how it goes

**Comment by jeswr** [comment]
Ok, that's fixed those tests (yay!). There is now a new error later on [file `'prolog.p'' does not exist](https://github.com/SWI-Prolog/npm-swipl-wasm/actions/runs/11958429109/job/33338317901?pr=787#step:6:1046); it looks like the file we provide is [prolog.pl](https://github.com/SWI-Prolog/npm-swipl-wasm/blob/3208c823f331f3789f48245d9ffdc5be98ca7528/dist/generateImage.ts#L18).

Was support for `.pl` extensions dropped?

**Comment by JanWielemaker** [comment]
Nothing changed there.    Could it be that I made a mistake with SWI-Prolog/swipl-devel@2910776f8c0efa001c9c16866fce09b4071e9f16?    It seems that the node invocations of SWI-Prolog during the build work fine, but I'm not 100% sure they use this.  Do you see anything wrong with this change?

**Comment by jeswr** [comment]
Looking now - I also think that the `-q` flag isn't being picked up see [here](https://github.com/SWI-Prolog/npm-swipl-wasm/actions/runs/11996793058/job/33441674225#step:6:4245)

**Comment by JanWielemaker** [comment]
Yip.  The last character of each argument was lost.   Fixed with SWI-Prolog/swipl-devel@848bc2df48f1a224fb1ebf4fefdb8ee38584d3a2

**Comment by jeswr** [comment]
> Nothing changed there. Could it be that I made a mistake with [SWI-Prolog/swipl-devel@2910776](https://github.com/SWI-Prolog/swipl-devel/commit/2910776f8c0efa001c9c16866fce09b4071e9f16)? It seems that the node invocations of SWI-Prolog during the build work fine, but I'm not 100% sure they use this. Do you see anything wrong with this change?

@JanWielemaker yes - I ran the tests on the previous commit https://github.com/SWI-Prolog/swipl-devel/commit/d5192b2d20952d62de8b6829a7d719c1bc3c7af7 and they all pass and then fail on [SWI-Prolog/swipl-devel@2910776](https://github.com/SWI-Prolog/swipl-devel/commit/2910776f8c0efa001c9c16866fce09b4071e9f16)

**Comment by jeswr** [comment]
> Yip. The last character of each argument was lost. Fixed with [SWI-Prolog/swipl-devel@848bc2d](https://github.com/SWI-Prolog/swipl-devel/commit/848bc2df48f1a224fb1ebf4fefdb8ee38584d3a2)

Awesome - updated PR, lets see how the CI goes

**Comment by jeswr** [comment]
Seems to be fixed locally - thanks @JanWielemaker !

**Pull request merged**
