### PR TITLE
fix: update to swipl v9.1.14

### PR DESCRIPTION
**Pull request by jeswr**
fix: update to swipl v9.1.14

### CODE REVIEW

**Comment by jeswr** [comment]
@JanWielemaker it looks like `ctest` is failing when trying to build of swipl v9.1.14 (see https://github.com/SWI-Prolog/npm-swipl-wasm/actions/runs/5861949492/job/15892952044?pr=308#step:5:1948).

Is this a known / intentional breaking. If not do you have capacity to diagnose the issue?

**Comment by JanWielemaker** [comment]
> Is this a known / intentional breaking. If not do you have capacity to diagnose the issue?

No.  It is quite weird as there are very few possibly related changes.    We need the output of the tests though.   Can you add `--output-on-failure` to the ctest options?

**Comment by jeswr** [comment]
>  Can you add --output-on-failure to the ctest options?

Done. [The error](https://github.com/SWI-Prolog/npm-swipl-wasm/actions/runs/5864853936/job/15900659655?pr=308#step:5:1975) seems to consistently be:
```
#23 7.288 TypeError: Cannot read properties of undefined (reading 'ioctl_tiocgwinsz')
#23 7.288     at ___syscall_ioctl (/swipl-devel/build.wasm/src/swipl.js:1:69351)
```

**Comment by JanWielemaker** [comment]
> I suspect that this means you're using a global that is no longer available in emsdk v3.1.44

Possibly, but I did make changes that are related to ioctl(), so it could be my fault :smile: .    I'll first build with my somewhat older toolkit and see what happens.

**Comment by JanWielemaker** [comment]
Hmm.  Builds and tests fine with emsdk 3.1.37.  I'll upgrade and see what happens.

**Comment by JanWielemaker** [comment]
Reproduces.    Fixed with SWI-Prolog/swipl-devel@ebb733bf22ed52b61b431a1932884964bf9d9126
Seems 3.1.44 does provide the headers for ioctl `TIOCGWINSZ`, but not (all) the implementation, so I explicitly disabled that code for EMSCRIPTEN.   One of the annoyances of emsdk is that it claims to have more than it actually has :cry:    But, it seems to compile and run faster with this version :smile:

**Pull request closed without merging**
